# Generated by Django 3.1.7 on 2021-04-06 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(blank=True, max_length=500, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('professsion', models.CharField(blank=True, max_length=40, null=True)),
                ('hathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.hathway')),
            ],
        ),
    ]
